### PR TITLE
fix syntax errors in the docker compose yml file

### PR DESCRIPTION
**Pull request by drzaiusx11**
docker-compose up (docker v18.09.0) on mac & windows dies complaining about syntax errors in the docker compose yml file. this fixes the errors so it should work on all platforms

### CODE REVIEW

**Comment by rqelibari** [comment]
Hi @drzaiusx11,

thank you for your contribution. As far as I can see in the `docker-compose` [volume documentation](https://docs.docker.com/compose/compose-file/#volume-configuration-reference) only the colons inside the top-level `volumes` were missing, whereas the dot-slash `./` prefix declares a volume to be a relative path (relative to the `docker-compose.yml` file).
If you can remove the dot-slash prefixes, I will be more than happy to merge your changes :-)

**Comment by drzaiusx11** [comment]
Maybe I'm missing something, but if I remove the ./ from my volumes the services don't work.

If you leave out the ./ does that infer an external volume?

**Comment by rqelibari** [comment]
Is there any relevant output of the `docker-compose` command? What macOS version are you on? And what VM engine are you using for docker?

[Here](https://stackoverflow.com/questions/39763115/docker-named-volume-location-mac) is an example of a working `docker-compose.yml` file:

```yml
[...]
  wordpress:
    image: wordpress:latest
    ports:
      - "8000:80"
    volumes:
      - wordpress/:/var/www/html/
    [...]

volumes:
    wordpress:
```

**Comment by drzaiusx11** [comment]
After some digging it seems named volumes (the ones without the ./ prefix) aren't automatically created on certain storage engines. You manually need to call `docker volume create <volume name>`

My VM is virtual box I believe. I'll try and double check when I'm back in front of my dev box tonight (EST)

For portability do you think relative path might be better?

**Comment by drzaiusx11** [comment]
I'm on OSX Sierra 10.12

**Comment by drzaiusx11** [comment]
ok, so now after removing the ./ prefix from my volumes the servers actually startup without errors. I'm not sure why but only the one from docker hub is working, the image I built my self throws errors trying to connect to mongo (see my other bug task)

I'll go ahead and revert my relative-path changes to the volumes for now and resubmit the PR

**Pull request merged**
